apiVersion: apps/v1
kind: Deployment
metadata:
  name: mun-app
spec:
  selector:
    matchLabels:
      app: mun-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mun-app
    spec:
      containers:
        - name: mun-app
          resources: {}
          image: mrspex/helsingborg:mun-0.0.3
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_HOST
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: PUBLIC_DOMAIN
              value: localhost
          ports:
            - containerPort: 80
