---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ols
  namespace: prod
  labels:
    app: ols
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ols
  template:
    metadata:
      labels:
        app: ols
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: ols
          image: webbutvecklinghelsingborg/gitops:openlitespeed-0.0.3
          ports:
            - containerPort: 80